const db_materials = {
  pm: [
    { code: 'PM-00001', name: 'Active Energy 180gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00002', name: 'Active Energy 180gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00003', name: 'Active Energy 180gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00004', name: 'Active Energy 18gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00005', name: 'Active Energy 18gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00006', name: 'Active Energy 40gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00007', name: 'Active Energy 45gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00008', name: 'Active Energy 45gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00009', name: 'Additive Solvent', unit: 'Pcs', price: 0 },
    { code: 'PM-00010', name: 'Additive Special', unit: 'Pcs', price: 0 },
    { code: 'PM-00011', name: 'Additive (Wash Solution)', unit: 'Pcs', price: 0 },
    { code: 'PM-00012', name: 'Almond Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00013', name: 'Anarkoli Biscuit  Mini Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00014', name: 'Anarkoli Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00015', name: 'Anchor Dal Vaja Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00016', name: 'Apple Cake Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00017', name: 'Aromatic Chinigura Ricc 1kg Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00018', name: 'Aromatic Chinigura Rice 1kg Ctn(Export)', unit: 'Pcs', price: 0 },
    { code: 'PM-00019', name: 'Baby Toast Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00020', name: 'Baby Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00021', name: 'Bay Leaf 40gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00022', name: 'Bela Biscuits 250gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00023', name: 'Best Choice 180gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00024', name: 'Best Choice 180gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00025', name: 'Best Choice 180gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00026', name: 'Best Choice 80 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00027', name: 'Best Choice 80 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00028', name: 'Black Ink 1 Ltr', unit: 'Pcs', price: 0 },
    { code: 'PM-00029', name: 'Black Ink Special', unit: 'Pcs', price: 0 },
    { code: 'PM-00030', name: 'Bombay Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00031', name: 'Bottle Cap for all preform', unit: 'Pcs', price: 0 },
    { code: 'PM-00032', name: 'Butter Toast 200gm X 6pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00033', name: 'Butter Toast 200gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00034', name: 'Butter Toast 250gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00035', name: 'C.Club Fruit Plus Pineapple 25 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00036', name: 'C.Club Fruit Plus Pineapple 25 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00037', name: 'Chaina Bela PP Poly', unit: 'Kg', price: 0 },
    { code: 'PM-00038', name: 'Chanachur Jhal 200gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00039', name: 'Chanachur Jhal 300gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00040', name: 'Chanachur Jhal 350gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00041', name: 'Chanachur Misti 350gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00042', name: 'Chanachur Special 180gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00043', name: 'Choco Fun Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00044', name: 'Choco Milk Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00045', name: 'Chusni Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00046', name: 'Chutki Shemai 150gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00047', name: 'Chutki Shemai 180gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00048', name: 'Chutki Shemai 350gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00049', name: 'Chutki Shemai 350gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00051', name: 'Chutki Shemai 400gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00052', name: 'Chutki Shemai 400gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00053', name: 'Coconut Choco Slice Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00054', name: 'Coconut Choco Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00055', name: 'Coconut Cookies 100gm Master Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00056', name: 'Coconut Cookies 90gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00057', name: 'Coconut Cookies 90gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00058', name: 'Coconut Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00059', name: 'Coconut Slice Toast Medium Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00060', name: 'Coconut Slice Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00061', name: 'Coconut Toast Medium Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00062', name: 'Confectionary Biscuits Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00063', name: 'Confectionery Biscuits Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00064', name: 'Cookies Biscuitsn Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00065', name: 'Cookies Biscuits Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00066', name: 'Cream Club Choco Plus 18gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00067', name: 'Cream Club Choco Plus 18gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00068', name: 'Cream Club Choco Plus 40gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00069', name: 'Cream Club Choco Plus 40gm Wrapper', unit: 'Kg', price: 0 },
    {
      code: 'PM-00070',
      name: 'Cream Club Fruit Plus Pineapple 20gm Carton',
      unit: 'Pcs',
      price: 0
    },
    {
      code: 'PM-00071',
      name: 'Cream Club Fruit Plus Pineapple 20gm Wrapper',
      unit: 'Kg',
      price: 0
    },
    {
      code: 'PM-00072',
      name: 'Cream Club Fruit Plus Pineapple 42gm Carton',
      unit: 'Pcs',
      price: 0
    },
    {
      code: 'PM-00073',
      name: 'Cream Club Fruit Plus Pineapple 42gm Wrapper',
      unit: 'Kg',
      price: 0
    },
    { code: 'PM-00074', name: 'Cream Roll Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00075', name: 'Cream Roll Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00076', name: 'Cup Cake Cup', unit: 'Pcs', price: 0 },
    { code: 'PM-00077', name: 'Cup Cake Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00078', name: 'Cutting Paper', unit: 'Kg', price: 0 },
    { code: 'PM-00079', name: 'Dairy Milk Chocolate 12gm Aluminum Paper', unit: 'Kg', price: 0 },
    { code: 'PM-00080', name: 'Dairy Milk Chocolate 24gm Aluminum Paper', unit: 'Kg', price: 0 },
    { code: 'PM-00081', name: 'Dairy Milk Chocolate 6gm Aluminum Paper', unit: 'Kg', price: 0 },
    { code: 'PM-00082', name: 'Dal Vaja 25gm Foil Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00083', name: 'Date Token Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00084', name: 'Drinks 125ml HDPE Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00085', name: 'Drinks Drinking Straw', unit: 'Kg', price: 0 },
    { code: 'PM-00086', name: 'Drinks Outer Poly 150ml 215mm', unit: 'Kg', price: 0 },
    { code: 'PM-00087', name: 'Drinks Outer Poly 150Ml 370mm', unit: 'Kg', price: 0 },
    { code: 'PM-00088', name: 'Dry Cake 100gm Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00089', name: 'Dry Cake 350gm ATC Box(Export)', unit: 'Pcs', price: 0 },
    { code: 'PM-00090', name: 'Dry Cake 350gm ATC Inner Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00091', name: 'Dry Cake 350gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00092', name: 'Dry Cake 350gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00093', name: 'Dry Cake 350gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00094', name: 'Dry Cake 40gm Master Ctn(Export)', unit: 'Pcs', price: 0 },
    { code: 'PM-00095', name: 'Dry Cake 500gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00096', name: 'Dry Cake Biscuit Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00097', name: 'Dry Cake Mini 30gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00098', name: 'Dry Cake Mini 30gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00099', name: 'Dry Cake Mini Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00100', name: 'Dry Cake Paper Ream', unit: 'Ream', price: 0 },
    { code: 'PM-00101', name: 'Dry Cake Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00102', name: 'Dry Chilli 40gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00103', name: 'Dry Chilli 80gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00104', name: 'Dum Drinks Aluminum Sealing Foil', unit: 'Pcs', price: 0 },
    { code: 'PM-00105', name: 'Elachi Biscuits 45gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00106', name: 'Elachi Biscuits 45gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00107', name: 'Family Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00108', name: 'Family Cake 100gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00109', name: 'Family Cake 200gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00110', name: 'Family Cake 90gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00111', name: 'Family Cake 90gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00112', name: 'Family Cake Pouch', unit: 'Kg', price: 0 },
    {
      code: 'PM-00113',
      name: 'Family Time Butter Cookies 900gm Sticker (Export)',
      unit: 'Pcs',
      price: 0
    },
    { code: 'PM-00114', name: 'Fruit Bun Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00115', name: 'Fruit Cake Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00116', name: 'Fruit Cookies Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00117', name: 'F.Time Butter Cookies 900gm Ctn', unit: 'Pcs', price: 0 },
    { code: 'PM-00118', name: 'F.Time Butter Cookies 900gm Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00119', name: 'F. Time Butter Cookies  Jar 900 gm Level', unit: 'Pcs', price: 0 },
    { code: 'PM-00120', name: 'F.Time Chocolate Cookies Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00121', name: 'F.Time Chocolate Cookies Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00122', name: 'F.Time Chocolate/Milk Cookies Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00123', name: 'F.Time Milk Cookies Ctn', unit: 'Pcs', price: 0 },
    { code: 'PM-00124', name: 'F.Time Milk Cookies Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00125', name: 'Ghee Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00126', name: 'Glassine Paper', unit: 'Pcs', price: 0 },
    { code: 'PM-00127', name: 'Gum', unit: 'Kg', price: 0 },
    { code: 'PM-00128', name: 'Gum Tape 1"(Both Side)', unit: 'Pcs', price: 0 },
    { code: 'PM-00129', name: 'Gum Tape 2"', unit: 'Pcs', price: 0 },
    { code: 'PM-00130', name: 'Gum Tape 2.5"', unit: 'Pcs', price: 0 },
    { code: 'PM-00131', name: 'Gum Tape 3/4"', unit: 'Pcs', price: 0 },
    { code: 'PM-00132', name: 'Gum Tape 1', unit: 'Pcs', price: 0 },
    { code: 'PM-00133', name: 'HDPE Inner Poly 21"x18"', unit: 'Kg', price: 0 },
    { code: 'PM-00134', name: 'HDPE Master Poly 40"x21.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00135', name: 'HDPE Outer Poly 21.5"x36"', unit: 'Kg', price: 0 },
    { code: 'PM-00136', name: 'HDPE-Resin', unit: 'Kg', price: 0 },
    { code: 'PM-00137', name: 'Honey Queen Bread Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00138', name: 'Ice Lolly 1600ml Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00139', name: 'Ice Lolly 1600ml Jar Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00140', name: 'Ice Lolly 1600ml Jar Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00141', name: 'Ice Lolly 480ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00142', name: 'Ice Lolly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00143', name: 'Ice Loly 40ml Tube', unit: 'Pcs', price: 0 },
    { code: 'PM-00144', name: 'Ice Pop Jar Level', unit: 'Pcs', price: 0 },
    { code: 'PM-00145', name: 'Ice Pop Tube', unit: 'Kg', price: 0 },
    { code: 'PM-00146', name: "Inner Poly 16'' x 19''", unit: 'Kg', price: 0 },
    { code: 'PM-00147', name: "Inner Poly 17'' x 19.5''", unit: 'Kg', price: 0 },
    { code: 'PM-00148', name: "Inner Poly 18' x 15''", unit: 'Kg', price: 0 },
    { code: 'PM-00149', name: "Inner Poly 21.5'' x 16''", unit: 'Kg', price: 0 },
    { code: 'PM-00150', name: 'Inner Poly 23"x14"', unit: 'Kg', price: 0 },
    { code: 'PM-00151', name: 'Inner Poly 7.5"X11.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00152', name: 'Inner Poly 8"x11.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00153', name: 'Inner Poly Cutting Paper fitting 6"x8"', unit: 'Kg', price: 0 },
    { code: 'PM-00154', name: 'King Cookies 40gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00155', name: 'King Cookies 40gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00156', name: 'King Cookies 50gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00157', name: 'King Cookies Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00158', name: 'King Jar Cookies Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00159', name: 'King Jar Cookies Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00160', name: 'King Jar Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00161', name: 'Laddu 500gm HDPE Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00162', name: 'Lascha Shemai 200gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00163', name: 'Lascha Shemai 200gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00164', name: 'Lascha Shemai 200gm Pouch(Local)', unit: 'Kg', price: 0 },
    { code: 'PM-00165', name: 'Lascha Shemai Premium 500gm Bag', unit: 'Pcs', price: 0 },
    { code: 'PM-00166', name: 'Lascha Shemai Premium 500gm Ctn', unit: 'Pcs', price: 0 },
    { code: 'PM-00167', name: 'Lascha Shemai Premium 500gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00168', name: 'Lascha Shemai Special 5kg Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00169', name: 'Lexus 15gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00170', name: 'Lexus 15gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00171', name: 'Lexus 180gm ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00173', name: 'Lexus 65 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00174', name: 'Lexus 65 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00175', name: 'Lis Cock Vermicelli Shemai 200gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00176', name: 'Lis Cock Vermicelli ShemaiÂ 200gmÂ Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00177', name: 'Lis Egg Noodles 120gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00178', name: 'Lis Egg Noodles 120gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00179', name: 'Lis Salty Biscuits 220gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00180', name: 'Lis Salty Biscuits 220gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00181', name: 'Lis Salty Biscuits 350gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00182', name: 'Lis Salty Biscuits 350gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00183', name: 'Lis Special Vermicelli Shemai 400gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00184', name: 'Lis Vermicelli Shemai 200gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00185', name: 'Lis Vermicelli Shemai 200gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00186', name: 'Lychee Drinks Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00187', name: 'Lychee Drinks Shrink Label', unit: 'Kg', price: 0 },
    { code: 'PM-00188', name: 'Lychee Drinks Shrink Label Dum 125ml', unit: 'Kg', price: 0 },
    { code: 'PM-00189', name: 'Lychee Drinks Shrink Label Dum 150ml', unit: 'Kg', price: 0 },
    { code: 'PM-00190', name: 'Lychee Drinks Shrink Outer Poly 350mm', unit: 'Kg', price: 0 },
    { code: 'PM-00191', name: 'Mango Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00192', name: 'Master Poly 24"x20"', unit: 'Kg', price: 0 },
    { code: 'PM-00193', name: "Master Poly 27'' x 41''", unit: 'Kg', price: 0 },
    { code: 'PM-00194', name: "Master Poly-27'' x 47''", unit: 'Kg', price: 0 },
    { code: 'PM-00195', name: 'Master Poly 34"X18"', unit: 'Kg', price: 0 },
    { code: 'PM-00196', name: "Master Poly 35'' x 26''", unit: 'Kg', price: 0 },
    { code: 'PM-00197', name: 'Master Poly 43"x22"', unit: 'Kg', price: 0 },
    { code: 'PM-00198', name: "Master Poly 47'' x 25''", unit: 'Kg', price: 0 },
    { code: 'PM-00199', name: 'Medicare Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00200', name: 'Milk Biscuits 45gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00201', name: 'Milk Biscuits 45gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00202', name: 'Milk Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00203', name: 'Milk Cookies Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00204', name: 'Misti Chanachur 400gm Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00205', name: 'Mixed Fruit Cake 250gm Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00206', name: 'Mixed Fruit Cake 280gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00207', name: 'Mixed Fruit Cake 300gm Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00208', name: 'Mixed Fruit Cake Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00209', name: 'Mixed Fruit Cake Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00210', name: 'Morning Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00211', name: 'Motor Vaja 15gm Warraper', unit: 'Kg', price: 0 },
    { code: 'PM-00212', name: 'Muri Toast Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00213', name: 'Muri Toast PP Poly', unit: 'Kg', price: 0 },
    { code: 'PM-00214', name: 'Mustard Oil 1000ml Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00215', name: 'Mustard Oil 1000ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00216', name: 'Mustard Oil 1000ml Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00217', name: 'Mustard Oil 200ml Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00218', name: 'Mustard Oil 200ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00219', name: 'Mustard Oil 200ml Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00220', name: 'Mustard Oil 250ml Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00221', name: 'Mustard Oil 250ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00222', name: 'Mustard Oil 250ml Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00223', name: 'Mustard Oil 400ml Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00224', name: 'Mustard Oil 400ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00225', name: 'Mustard Oil 400ml Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00226', name: 'Mustard Oil 500ml Bottle', unit: 'Pcs', price: 0 },
    { code: 'PM-00227', name: 'Mustard Oil 500ml Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00228', name: 'Mustard Oil 500ml Label', unit: 'Pcs', price: 0 },
    { code: 'PM-00229', name: 'Mustard Oil Bottle Cap', unit: 'Pcs', price: 0 },
    { code: 'PM-00230', name: 'Mustard Oil Cap Security Seal', unit: 'Kg', price: 0 },
    { code: 'PM-00231', name: 'Orange Cookies Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00232', name: 'Orange Drinks Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00233', name: 'Orange Drinks  Shirnk Level', unit: 'Kg', price: 0 },
    { code: 'PM-00234', name: 'Pet Lid', unit: 'Kg', price: 0 },
    { code: 'PM-00235', name: 'P.P Hand Gloves', unit: 'Pcs', price: 0 },
    { code: 'PM-00236', name: 'PP Poly 10"x14"', unit: 'Kg', price: 0 },
    { code: 'PM-00237', name: 'PP Poly 10"x19.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00238', name: 'PP Poly 10"x22"', unit: 'Kg', price: 0 },
    { code: 'PM-00239', name: 'PP Poly 18"x26"', unit: 'Kg', price: 0 },
    { code: 'PM-00240', name: 'PP Poly 20"x30"', unit: 'Kg', price: 0 },
    { code: 'PM-00241', name: 'PP Poly 22" X 30"', unit: 'Kg', price: 0 },
    { code: 'PM-00242', name: 'PP Poly 22"x36"', unit: 'Kg', price: 0 },
    { code: 'PM-00243', name: 'PP Poly 6.5"x12"', unit: 'Kg', price: 0 },
    { code: 'PM-00244', name: 'PP Poly 7"x12"', unit: 'Kg', price: 0 },
    { code: 'PM-00245', name: 'PP Poly 7"x15"', unit: 'Kg', price: 0 },
    { code: 'PM-00246', name: 'PP Poly 7"x19"', unit: 'Kg', price: 0 },
    { code: 'PM-00247', name: 'PP Poly 7.5"x16"', unit: 'Kg', price: 0 },
    { code: 'PM-00248', name: 'PP Poly 8"x10.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00249', name: 'PP Poly 8"x14.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00250', name: 'PP Poly 8"x15"', unit: 'Kg', price: 0 },
    { code: 'PM-00251', name: 'PP Poly 8"x18.5"', unit: 'Kg', price: 0 },
    { code: 'PM-00252', name: 'PP Poly 9"x14"', unit: 'Kg', price: 0 },
    { code: 'PM-00253', name: 'PP Poly 9"x19"', unit: 'Kg', price: 0 },
    { code: 'PM-00254', name: 'PP Poly 9"x22"', unit: 'Kg', price: 0 },
    { code: 'PM-00255', name: 'PP Print Poly "5x10"', unit: 'Kg', price: 0 },
    { code: 'PM-00256', name: 'PP Print Poly 10" x 14"', unit: 'Kg', price: 0 },
    { code: 'PM-00257', name: 'PP Print Poly 12" x 18"', unit: 'Kg', price: 0 },
    { code: 'PM-00258', name: 'PP Print Poly 5"x6"', unit: 'Kg', price: 0 },
    { code: 'PM-00259', name: 'PP Print Poly 5.5" x 10"', unit: 'Kg', price: 0 },
    { code: 'PM-00260', name: 'PP Print Poly 6" x 10"', unit: 'Kg', price: 0 },
    { code: 'PM-00261', name: 'PP Print Poly 7" x 9"', unit: 'Kg', price: 0 },
    { code: 'PM-00262', name: 'PP Print Poly 8" x 13"', unit: 'Kg', price: 0 },
    { code: 'PM-00263', name: 'PP Print Poly 9" x 14"', unit: 'Kg', price: 0 },
    { code: 'PM-00264', name: 'Preform Bottle 1000ml (24gm) Water', unit: 'Pcs', price: 0 },
    { code: 'PM-00265', name: 'Preform Bottle 2000ml (48gm) Water', unit: 'Pcs', price: 0 },
    { code: 'PM-00266', name: 'Preform Bottle 330ml (14gm) Water', unit: 'Pcs', price: 0 },
    { code: 'PM-00267', name: 'Preform Bottle 500ml (16gm) Water', unit: 'Pcs', price: 0 },
    { code: 'PM-00268', name: 'Premium Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00269', name: 'Puffed Rice 250gm HDPE Poly 50x25', unit: 'Kg', price: 0 },
    { code: 'PM-00270', name: 'Puffed Rice 250gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00271', name: 'Puffed Rice 500gm HDPE Poly 39x29', unit: 'Kg', price: 0 },
    { code: 'PM-00272', name: 'Puffed Rice 500gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00273', name: 'PVC Lid', unit: 'Kg', price: 0 },
    { code: 'PM-00274', name: 'PVC Sheet', unit: 'Kg', price: 0 },
    { code: 'PM-00275', name: 'Salted Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00276', name: 'Salted Special Biscuit Mini Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00277', name: 'Salted Special Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00278', name: 'Sandwich Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00279', name: 'Seventy Cookies Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00280', name: 'Shahi Ban Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00281', name: 'Shrink Label 1000 MLWater', unit: 'Kg', price: 0 },
    { code: 'PM-00282', name: 'Shrink Label 1500 ML Water', unit: 'Kg', price: 0 },
    { code: 'PM-00283', name: 'Shrink Label 2000 ML Water', unit: 'Kg', price: 0 },
    { code: 'PM-00284', name: 'Shrink Label 330 ML Water', unit: 'Kg', price: 0 },
    { code: 'PM-00285', name: 'Shrink Label 500 ML Water', unit: 'Kg', price: 0 },
    { code: 'PM-00286', name: 'Shrink Outer Poly 1000ml Water 500mm', unit: 'Kg', price: 0 },
    { code: 'PM-00287', name: 'Shrink Outer Poly 1500ml Water 410mm', unit: 'Kg', price: 0 },
    { code: 'PM-00288', name: 'Shrink Outer Poly 330/2000ml  Water 480mm', unit: 'Kg', price: 0 },
    { code: 'PM-00289', name: 'Shrink Outer Poly 500ml Water 580mm', unit: 'Kg', price: 0 },
    { code: 'PM-00290', name: 'Special Banana Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00291', name: 'Special Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00292', name: 'Special Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00293', name: 'Special Bun Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00294', name: 'Special Butter Bun Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00295', name: 'Special Cake 350gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00296', name: 'Special Cake 350gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00297', name: 'Special Cake Mini Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00298', name: 'Special Chocolate Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00299', name: 'Special Coconut Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00300', name: 'Special Daya Salt Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00301', name: 'Special Dry Cake 500gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00302', name: 'Special Dry Cake 800gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00303', name: 'Special Dry Cake Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00304', name: 'Special Dry Cake Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00305', name: 'Special Dry Toast Mini Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00306', name: 'Special Dry Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00307', name: "Special Food's Sticker", unit: 'Pcs', price: 0 },
    { code: 'PM-00308', name: "Special Food's Tray", unit: 'Pcs', price: 0 },
    { code: 'PM-00309', name: 'Special Khasta Bela  Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00310', name: 'Special Malai Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00311', name: 'Special Mamar Bela Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00312', name: 'Special Milk Malai Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00313', name: 'Special Mix Chips Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00314', name: 'Special Narikel Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00315', name: 'Special Noni Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00316', name: 'Special Pasty Cake Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00317', name: 'Special Plain Cookies Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00318', name: 'Special Small Malai Toast Sticke', unit: 'Pcs', price: 0 },
    { code: 'PM-00319', name: 'Special Super Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00320', name: 'Special Taja Salted Biscuit Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00321', name: 'Special Tin Kona Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00322', name: 'Special Toast 180gm X 6pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00323', name: 'Special Toast 250gm X 6pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00324', name: 'Special Toast 250gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00325', name: 'Special Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00326', name: 'Spices 200gm Jar With Cap', unit: 'Pcs', price: 0 },
    { code: 'PM-00327', name: 'Stick Noodles Mix Masala Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00328', name: 'Stick Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00329', name: 'Super Bread Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00330', name: 'Sweet Patis Round Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00331', name: 'Sweet Toast 250gm X 12pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00332', name: 'Sweet Toast 350gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00333', name: 'Tea Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00334', name: 'Tiffin Cake Chocolate 12 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00335', name: 'Tiffin Cake Chocolate 12 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00336', name: 'Tiffin Cake Chocolate ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00337', name: 'Tiffin Cake Chocolate Family Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00338', name: 'Tiffin Cake Milk 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00339', name: 'Tiffin Cake Milk 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00340', name: 'Tiffin Cake Milk 20gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00341', name: 'Tiffin Cake Milk -20gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00342', name: 'Tiffin Cake Milk ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00343', name: 'Tiffin Cake Milk Family Ctn', unit: 'Pcs', price: 0 },
    { code: 'PM-00344', name: 'Tiffin Cake Mix ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00345', name: 'Tiffin Cake Mix Family Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00346', name: 'Tiffin Cake PVC Shrink Outer Poly', unit: 'Kg', price: 0 },
    { code: 'PM-00347', name: 'Tiffin Cake Vanilla 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00348', name: 'Tiffin Cake Vanilla 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00349', name: 'Tiffin Cake Vanilla ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00350', name: 'Tiffin Cake Vanilla Family Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00351', name: 'Til Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00352', name: 'Tim Tom Chicken Noodles 150gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00353', name: 'Tim Tom Chicken Noodles 150gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00354', name: 'Tim Tom Dairy Milk Chocolate 6gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00355', name: 'Tim Tom Dairy Milk Chocolate 6gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00356', name: 'Tim Tom Dairy Milk Chocolate 6gm ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00357', name: 'Tim Tom Ghee Toast 15gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00358', name: 'Tim Tom Ghee Toast 15gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00359', name: 'Tim Tom Hot Chanachur Family 150gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00360', name: 'Tim Tom Hot Chanachur 75gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00361', name: 'Tim Tom Hot Chanachur 12gm  Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00362', name: 'Tim Tom Milky Energy 18gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00363', name: 'Tim Tom Milky Energy 18gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00364', name: 'Tim Tom Motor Vaja 15gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00365', name: 'Tin Kona Toast PP Poly', unit: 'Kg', price: 0 },
    { code: 'PM-00366', name: 'Toffs 255 gm Inner Foil', unit: 'Kg', price: 0 },
    { code: 'PM-00367', name: 'Toffs 255 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00369', name: 'Valencia Orange 135 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00370', name: 'Valencia Orange 135gm Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00371', name: 'Valencia Orange 135 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00372', name: 'Valencia Orange 45 gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00373', name: 'Valencia Orange 45 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00374', name: 'Vanilla Toast Mini Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00375', name: 'Vanilla Toast Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00376', name: 'Vanilla Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00377', name: 'Vermicelli Shemai Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00378', name: 'Vermicelli Shemai Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00379', name: 'Wafer Paper Board (Top)', unit: 'Pcs', price: 0 },
    { code: 'PM-00380', name: 'Wafer Tim Tom Chocolate Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00381', name: 'Wafer Tim Tom Chocolate Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00382', name: 'Wafer Tim Tom Vanilla Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00383', name: 'Wafer Tim Tom Vanilla Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00384', name: 'White Bread Poly Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00385', name: 'Yellow Slice Toast Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00386', name: 'Zafran Aloo Bhujia 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00387', name: 'Zafran Basil Seeds 100gm Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00388', name: 'Zafran Basil Seeds 24pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00389', name: 'Zafran Basil Seeds 48pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00390', name: 'Zafran Bay Leaf 100gm Carton', unit: 'Pcs', price: 0 },
    {
      code: 'PM-00391',
      name: 'Zafran Bombay Vermicilli Shemai 200gm Carton',
      unit: 'Pcs',
      price: 0
    },
    { code: 'PM-00392', name: 'Zafran Bombay Vermicilli Shemai 200gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00393', name: 'Zafran Chanachur Jhal 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00394', name: 'Zafran Chanachur Jhal 150gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00395', name: 'Zafran Chanachur Jhal 75gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00396', name: 'Zafran Chanachur Jhal 75gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00397', name: 'Zafran Chanachur Special 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00398', name: 'Zafran Chanachur Special 150gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00399', name: 'Zafran Chanachur Special 75gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00400', name: 'Zafran Dairy Milk Chocolate 12gm ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00401', name: 'Zafran Dairy Milk Chocolate 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00402', name: 'Zafran Dairy Milk Chocolate 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00403', name: 'Zafran Dairy Milk Chocolate 24gm ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00404', name: 'Zafran Dairy Milk Chocolate 24gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00405', name: 'Zafran Dairy Milk Chocolate 24gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00406', name: 'Zafran Dairy Milk Chocolate 6gm ATC Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00407', name: 'Zafran Dairy Milk Chocolate 6gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00408', name: 'Zafran Dairy Milk Chocolate 6gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00409', name: 'Zafran Dal Vaja 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00410', name: 'Zafran Drinks Aluminum Sealing Foil', unit: 'Kg', price: 0 },
    { code: 'PM-00413', name: 'Zafran Ghee Toast 15gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00414', name: 'Zafran Ghee Toast 15gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00415', name: 'Zafran Sat Isabgol 100gm Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00416', name: 'Zafran Sat Isabgul 24pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00417', name: 'Zafran Sat Isabgul 48pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00418', name: 'Preform Bottle 1500ml (36gm) Water', unit: 'Pcs', price: 0 },
    { code: 'PM-00419', name: 'TimTom Jhal Chanachur 20gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00420', name: 'Zafran Jhal Chanachur 25gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00421', name: 'Tim Tom Cup Cake Vanilla 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00422', name: 'Tim Tom Cup Cake Vanilla 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00423', name: 'Zafran Egg Noodles 120gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00424', name: 'Zafran Egg Noodles 120gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00425', name: 'Tim Tom Choco Cake Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00426', name: 'Tim Tom Milk Wafer 15g Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00428', name: 'Tim Tom Super Duper 45g Wrapper', unit: 'Kg', price: 0 },
    {
      code: 'PM-00429',
      name: 'Tim Tom Chocofil Chocolate Cream 38g Wrapper',
      unit: 'Kg',
      price: 0
    },
    {
      code: 'PM-00430',
      name: 'Tim Tom Chocofil Chocolate Cream 18g Wrapper',
      unit: 'Kg',
      price: 0
    },
    { code: 'PM-00431', name: 'TimTom Coconut Cookies 72gm', unit: 'Kg', price: 0 },
    { code: 'PM-00432', name: 'Zafran Active Energy 60gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00433', name: 'Zafran Cream Club Choco Plus 60gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00434', name: 'Zafran Elachi Biscuits 60gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00435', name: 'Zafran Lexus 35gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00436', name: 'Zafran Lexus 60gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00437', name: 'Zafran Valencia Orange 60gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00438', name: 'Zafran Special Dry Cake 70gm Inner Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00439', name: 'Zafran Special Dry Cake 70gm Box', unit: 'Pcs', price: 0 },
    { code: 'PM-00440', name: 'Zafran Super Fun 40gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00441', name: 'Shipping Mark Sticker (KSA)', unit: 'Kg', price: 0 },
    { code: 'PM-00442', name: 'Tim Tom Dry Cake Mini 25gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00443', name: 'Tim Tom Dry Cake Mini 25gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00444', name: 'Tim Tom Super Energy 45gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00445', name: 'Tim Tom Super Energy 45gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00446', name: 'Zafran Lexus 35gmX 24pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00447', name: 'Lexus Standard Tray', unit: 'Pcs', price: 0 },
    { code: 'PM-00448', name: 'Tim Tom Super Energy 180gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00449', name: 'Tim Tom Super Energy 180gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00450', name: 'Special Toast 200gm X 12pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00451', name: 'Special Toast Paper Board', unit: 'Pcs', price: 0 },
    { code: 'PM-00452', name: 'Tim Tom Aloo Bhujia 20 gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00453', name: 'Family Time Butter Cookies 600gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00454', name: 'Family Time Butter Cookies 600gm Jar', unit: 'Pcs', price: 0 },
    { code: 'PM-00455', name: 'Timtom Lascha Shemai 200gm Pouch', unit: 'Kg', price: 0 },
    { code: 'PM-00456', name: 'Tim Tom Milk Wafer 15gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00457', name: 'Inner Poly 28"x18"', unit: 'Kg', price: 0 },
    { code: 'PM-00458', name: 'Master Poly 38"x46"', unit: 'Kg', price: 0 },
    { code: 'PM-00459', name: 'Tim Tom Aloo Bhujia 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00460', name: 'Tim Tom Aloo Bhujia 25gm wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00461', name: 'Tim Tom Dal Vaja 13gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00462', name: 'Tim Tom Milk Cake 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00463', name: 'Tim Tom Milk Cake 12gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00464', name: 'Tim Tom Tiffin Cake Chocolate 12gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00465', name: 'Tim Tom Fruitfill Pineapple 18gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00466', name: 'Tim Tom Fruitfill Pineapple 18gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00467', name: 'Tim Tom Fruitfill Pineapple 38gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00468', name: 'Tim Tom Fruitfill Pineapple 38gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00469', name: 'Tim Tom Lexus 35gm X 24pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00470', name: 'Tim Tom Lexus Mini 15gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00471', name: 'Tim Tom Lexus Mini 15gm Wrapper', unit: 'Pcs', price: 0 },
    { code: 'PM-00472', name: 'Tim Tom Lexus 35gm Wrapper', unit: 'Pcs', price: 0 },
    { code: 'PM-00473', name: 'Tim Tom Orange 150gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00474', name: 'Tim Tom Valencia Orange 150gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00475', name: 'Tim Tom Orange 40gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00476', name: 'Tim Tom Valencia Orange 40gm Wrapper', unit: 'Kg', price: 0 },
    { code: 'PM-00477', name: 'Tim Tom Super Duper 45gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00478', name: 'Zafran Lexus Biscuits 60gm X 24pcs Carton', unit: 'Pcs', price: 0 },
    {
      code: 'PM-00479',
      name: 'Zafran Lexus Biscuits 60gm X 96pcs Master Carton',
      unit: 'Pcs',
      price: 0
    },
    { code: 'PM-00480', name: 'Zafran Super Fun 40gm X 24pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00481', name: 'Lexus 180gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00482', name: 'Butter Toast 200gm X 12pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00483', name: 'Butter Toast 250gm X 12pcs Carton Export', unit: 'Pcs', price: 0 },
    { code: 'PM-00484', name: 'Dry Cake 320gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00485', name: 'Special Toast 250gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00486', name: 'Sweet Toast 250gm X 6pcs Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00487', name: 'Tim Tom Butter Cookies 500gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00488', name: 'Tim Tom Butter Cookies 600gm Sticker', unit: 'Pcs', price: 0 },
    { code: 'PM-00489', name: 'Zafran Butter Cookies 500gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00490', name: 'Zafran Special Dry Cake 70gm Carton Export', unit: 'Pcs', price: 0 },
    { code: 'PM-00491', name: 'Dry Cake 350gm Carton (12Pcs)-Export', unit: 'Pcs', price: 0 },
    { code: 'PM-00492', name: 'Dry Cake 40gm Carton (Master)-Export', unit: 'Pcs', price: 0 },
    { code: 'PM-00493', name: 'Family Time Butter Cookies 900gm Carton', unit: 'Pcs', price: 0 },
    { code: 'PM-00494', name: 'Family Time Cookies Paper Board', unit: 'Pcs', price: 0 },
    { code: 'PM-00495', name: 'Lascha Shemai 200gm Sticker', unit: 'Pcs', price: 0 },
    {
      code: 'PM-00496',
      name: 'Zafran Lascha Semai 180gm X 40pcs Carton Export',
      unit: 'Pcs',
      price: 0
    },
    { code: 'PM-00497', name: 'Vermicelli 200gm Sticker', unit: 'Pcs', price: 0 }
  ],
  rm: [
    { code: 'RM-00001', name: 'Alcohol (IPA)', unit: 'Kg', price: 0 },
    { code: 'RM-00002', name: 'Ammonium Bi Carbonate', unit: 'Kg', price: 0 },
    { code: 'RM-00003', name: 'Anchor Dal', unit: 'Kg', price: 0 },
    { code: 'RM-00004', name: 'Apple Green Colour', unit: 'Kg', price: 0 },
    { code: 'RM-00005', name: 'Aromatic Rice', unit: 'Kg', price: 0 },
    { code: 'RM-00006', name: 'Ascorbic Acid', unit: 'Kg', price: 0 },
    { code: 'RM-00007', name: 'Aspartame', unit: 'Kg', price: 0 },
    { code: 'RM-00008', name: 'Basil Seed', unit: 'Kg', price: 0 },
    { code: 'RM-00009', name: 'Bay Leaf', unit: 'Kg', price: 0 },
    { code: 'RM-00010', name: 'Beta Carotene', unit: 'Kg', price: 0 },
    { code: 'RM-00011', name: 'Bit Salt', unit: 'Kg', price: 0 },
    { code: 'RM-00012', name: 'Black Cumin', unit: 'Kg', price: 0 },
    { code: 'RM-00013', name: 'Black Pepper', unit: 'Kg', price: 0 },
    { code: 'RM-00014', name: 'Bread Improver', unit: 'Kg', price: 0 },
    { code: 'RM-00015', name: 'Butta Belly Flavour (Aroma)', unit: 'Kg', price: 0 },
    { code: 'RM-00016', name: 'Butter Cream', unit: 'Kg', price: 0 },
    { code: 'RM-00017', name: 'Butter Flavour (Dohler)', unit: 'Kg', price: 0 },
    { code: 'RM-00018', name: 'Butter Flavour (SM350)', unit: 'Kg', price: 0 },
    { code: 'RM-00019', name: 'Butter Flavour (Symega)', unit: 'Kg', price: 0 },
    { code: 'RM-00020', name: 'Butter Oil', unit: 'Kg', price: 0 },
    { code: 'RM-00021', name: 'Butter Oil Substitute', unit: 'Kg', price: 0 },
    { code: 'RM-00022', name: 'Butter Solid', unit: 'Kg', price: 0 },
    { code: 'RM-00023', name: 'Cake Emulsifier', unit: 'Kg', price: 0 },
    { code: 'RM-00024', name: 'Cake Gel', unit: 'Kg', price: 0 },
    { code: 'RM-00025', name: 'Cake Super Flavour JWI', unit: 'Kg', price: 0 },
    { code: 'RM-00026', name: 'Calcium Carbonate', unit: 'Kg', price: 0 },
    { code: 'RM-00027', name: 'Calcium Propionate', unit: 'Kg', price: 0 },
    { code: 'RM-00028', name: 'Cardamom', unit: 'Kg', price: 0 },
    { code: 'RM-00029', name: 'Cardamom Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00030', name: 'Caustic Soda', unit: 'Kg', price: 0 },
    { code: 'RM-00031', name: 'Chocolate Brown Color-6059', unit: 'Kg', price: 0 },
    { code: 'RM-00032', name: 'Chocolate Brown Color-815', unit: 'Kg', price: 0 },
    { code: 'RM-00033', name: 'Chocolate Chips', unit: 'Kg', price: 0 },
    { code: 'RM-00034', name: 'Chocolate Flavour (KH Robers)', unit: 'Kg', price: 0 },
    { code: 'RM-00035', name: 'Chocolate Flavour (Symrise)', unit: 'Kg', price: 0 },
    { code: 'RM-00036', name: 'Chocolate Paste', unit: 'Kg', price: 0 },
    { code: 'RM-00037', name: 'Chutki Shemai', unit: 'Kg', price: 0 },
    { code: 'RM-00038', name: 'Cinnamon', unit: 'Kg', price: 0 },
    { code: 'RM-00039', name: 'Citric Acid ANO', unit: 'Kg', price: 0 },
    { code: 'RM-00040', name: 'Citric Acid Mono', unit: 'Kg', price: 0 },
    { code: 'RM-00041', name: 'Cloudifier Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00042', name: 'Cocoa Powder CM-1000', unit: 'Kg', price: 0 },
    { code: 'RM-00043', name: 'Cocoa Powder BT-910', unit: 'Kg', price: 0 },
    { code: 'RM-00044', name: 'Cocoa Powder PD-4011', unit: 'Kg', price: 0 },
    { code: 'RM-00045', name: 'Coconut Flavour (Aroma)', unit: 'Kg', price: 0 },
    { code: 'RM-00046', name: 'Coconut Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00047', name: 'Condensed Milk', unit: 'Kg', price: 0 },
    { code: 'RM-00048', name: 'Condensed Milk Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00049', name: 'Cracker Enzyme', unit: 'Kg', price: 0 },
    { code: 'RM-00050', name: 'Cumin Seed', unit: 'Kg', price: 0 },
    { code: 'RM-00051', name: 'Curry Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00052', name: 'Custard Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00053', name: 'Dalda Hard', unit: 'Kg', price: 0 },
    { code: 'RM-00054', name: 'Dalda Soft', unit: 'Kg', price: 0 },
    { code: 'RM-00055', name: 'Dry Ginger', unit: 'Kg', price: 0 },
    { code: 'RM-00056', name: 'Egg', unit: 'Kg', price: 0 },
    { code: 'RM-00057', name: 'Egg Seasoning Masala', unit: 'Kg', price: 0 },
    { code: 'RM-00058', name: 'Egg Yellow Color', unit: 'Kg', price: 0 },
    { code: 'RM-00059', name: 'Flour A', unit: 'Kg', price: 0 },
    { code: 'RM-00060', name: 'Flour B', unit: 'Kg', price: 0 },
    { code: 'RM-00061', name: 'Flour C', unit: 'Kg', price: 0 },
    { code: 'RM-00062', name: 'Full Cream Milk Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00063', name: 'Garlic Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00064', name: 'Ghee', unit: 'Kg', price: 0 },
    { code: 'RM-00065', name: 'Ghee Flavour (H-YES)', unit: 'Kg', price: 0 },
    { code: 'RM-00066', name: 'Glucose Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00067', name: 'Glycerin', unit: 'Kg', price: 0 },
    { code: 'RM-00068', name: 'Hydrose', unit: 'Kg', price: 0 },
    { code: 'RM-00069', name: 'Isabgol', unit: 'Kg', price: 0 },
    { code: 'RM-00070', name: 'Jwain', unit: 'Kg', price: 0 },
    { code: 'RM-00071', name: 'King Milk Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00072', name: 'Lemon Flavour (Symrise)', unit: 'Kg', price: 0 },
    { code: 'RM-00073', name: 'Lemon Yellow Color 5670', unit: 'Kg', price: 0 },
    { code: 'RM-00074', name: 'Lentil (Mushur Dal)', unit: 'Kg', price: 0 },
    { code: 'RM-00075', name: 'Liquid Glucose', unit: 'Kg', price: 0 },
    { code: 'RM-00076', name: 'Lychee Flavour (Sluys )', unit: 'Kg', price: 0 },
    { code: 'RM-00077', name: 'Macaroni', unit: 'Kg', price: 0 },
    { code: 'RM-00078', name: 'Magic Massala', unit: 'Kg', price: 0 },
    { code: 'RM-00079', name: 'Mango Flavour( Sluys)', unit: 'Kg', price: 0 },
    { code: 'RM-00080', name: 'Marzarine', unit: 'Kg', price: 0 },
    { code: 'RM-00081', name: 'Milk Flavour (Fluys)', unit: 'Kg', price: 0 },
    { code: 'RM-00082', name: 'Milk Flavour (Kh Robers)', unit: 'Kg', price: 0 },
    { code: 'RM-00083', name: 'Mono Saccharin', unit: 'Kg', price: 0 },
    { code: 'RM-00084', name: 'Mug Dal', unit: 'Kg', price: 0 },
    { code: 'RM-00085', name: 'Non Dairy Creamer', unit: 'Kg', price: 0 },
    { code: 'RM-00086', name: 'Nutmeg (Jayfal)', unit: 'Kg', price: 0 },
    { code: 'RM-00087', name: 'Onion', unit: 'Kg', price: 0 },
    { code: 'RM-00088', name: 'Onion Chives', unit: 'Kg', price: 0 },
    { code: 'RM-00089', name: 'Onion Flavour (Symega)', unit: 'Kg', price: 0 },
    { code: 'RM-00090', name: 'Onion Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00091', name: 'Orange Emulation (Symrise)', unit: 'Kg', price: 0 },
    { code: 'RM-00092', name: 'Orange Flavour (Famous)', unit: 'Kg', price: 0 },
    { code: 'RM-00093', name: 'Orange Flavour (Sluys)', unit: 'Kg', price: 0 },
    { code: 'RM-00094', name: 'Orange red Colour', unit: 'Kg', price: 0 },
    { code: 'RM-00095', name: 'Palm Oil Super', unit: 'Kg', price: 0 },
    { code: 'RM-00096', name: 'Paraffin Oil', unit: 'Kg', price: 0 },
    { code: 'RM-00097', name: 'Pea (Dably )', unit: 'Kg', price: 0 },
    { code: 'RM-00098', name: 'Peanut Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00099', name: 'PGPR', unit: 'Kg', price: 0 },
    { code: 'RM-00100', name: 'Pineapple Flavour (Kh Roberts)', unit: 'Kg', price: 0 },
    { code: 'RM-00101', name: 'Potassium Sorbet', unit: 'Kg', price: 0 },
    { code: 'RM-00102', name: 'Puffed Rice', unit: 'Kg', price: 0 },
    { code: 'RM-00103', name: 'Pure Mustard Oil', unit: 'Kg', price: 0 },
    { code: 'RM-00104', name: 'Raw Peanut', unit: 'Kg', price: 0 },
    { code: 'RM-00105', name: 'Red Chilli Bogra', unit: 'Kg', price: 0 },
    { code: 'RM-00106', name: 'Red Chilli Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00107', name: 'Rice (Atop)', unit: 'Kg', price: 0 },
    { code: 'RM-00108', name: 'Rice Flakes (Chira)', unit: 'Kg', price: 0 },
    { code: 'RM-00109', name: 'Ring Chips', unit: 'Kg', price: 0 },
    { code: 'RM-00110', name: 'Salt (Narmal)', unit: 'Kg', price: 0 },
    { code: 'RM-00111', name: 'Salt (Super)', unit: 'Kg', price: 0 },
    { code: 'RM-00112', name: 'SMP', unit: 'Kg', price: 0 },
    { code: 'RM-00113', name: 'Sodium Acid Pyrophosphate', unit: 'Kg', price: 0 },
    { code: 'RM-00114', name: 'Sodium Benzoate', unit: 'Kg', price: 0 },
    { code: 'RM-00115', name: 'Sodium Bi Carbonate', unit: 'Kg', price: 0 },
    { code: 'RM-00116', name: 'Sodium Citrate', unit: 'Kg', price: 0 },
    { code: 'RM-00117', name: 'Sodium C.M.C', unit: 'Kg', price: 0 },
    { code: 'RM-00118', name: 'Sodium Mata Bi Sulphate', unit: 'Kg', price: 0 },
    { code: 'RM-00119', name: 'Sorbital', unit: 'Kg', price: 0 },
    { code: 'RM-00120', name: 'Soya Lecithin', unit: 'Kg', price: 0 },
    { code: 'RM-00121', name: 'Starch Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00122', name: 'Sugar', unit: 'Kg', price: 0 },
    { code: 'RM-00123', name: 'Sunset Yellow Color', unit: 'Kg', price: 0 },
    { code: 'RM-00124', name: 'Tapioca Starch', unit: 'Kg', price: 0 },
    { code: 'RM-00125', name: 'Tartarzen Yellow Color', unit: 'Kg', price: 0 },
    { code: 'RM-00126', name: 'TBHQ', unit: 'Kg', price: 0 },
    { code: 'RM-00127', name: 'Testing Salt', unit: 'Kg', price: 0 },
    { code: 'RM-00128', name: 'Titinium Di Oxide', unit: 'Kg', price: 0 },
    { code: 'RM-00129', name: 'Turmeric', unit: 'Kg', price: 0 },
    { code: 'RM-00130', name: 'Turmeric Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00131', name: 'Tutti Fruti Color', unit: 'Kg', price: 0 },
    { code: 'RM-00132', name: 'Vanilla Flavour (KH Robers)', unit: 'Kg', price: 0 },
    { code: 'RM-00133', name: 'Vanilla Flavour Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00134', name: 'Vanillin Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00135', name: 'Vegetable Fat', unit: 'Kg', price: 0 },
    { code: 'RM-00136', name: 'White Sesame', unit: 'Kg', price: 0 },
    { code: 'RM-00137', name: 'Xanthan Gum', unit: 'Kg', price: 0 },
    { code: 'RM-00138', name: 'Yeast Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00140', name: 'Chocolate Sweet Flavour', unit: 'Kg', price: 0 },
    { code: 'RM-00141', name: 'Butter Flavour (6.52549) Dohler', unit: 'Kg', price: 0 },
    { code: 'RM-00142', name: 'Finamul 4050L', unit: 'Kg', price: 0 },
    { code: 'RM-00143', name: 'Masking Flavour BFF', unit: 'Kg', price: 0 },
    { code: 'RM-00144', name: 'Milk Flavour OS (9.39175/9.06328) Dohler', unit: 'Kg', price: 0 },
    { code: 'RM-00145', name: 'Onion Flavour(Dohler)', unit: 'Kg', price: 0 },
    { code: 'RM-00146', name: 'Veron-HPP', unit: 'Kg', price: 0 },
    { code: 'RM-00147', name: 'Lychee Flavour-0164 (Symrise)', unit: 'Kg', price: 0 },
    { code: 'RM-00148', name: 'Milk Flavour IFF', unit: 'Kg', price: 0 },
    { code: 'RM-00149', name: 'Cheese Powder', unit: 'Kg', price: 0 },
    { code: 'RM-00150', name: 'Sunshine Flour(Gluten-27%-28%)', unit: 'Kg', price: 0 },
    { code: 'RM-00151', name: 'Egg Masala Seasoning', unit: 'Kg', price: 0 },
    { code: 'RM-00152', name: 'Palm Kernel Oil RBD', unit: 'Kg', price: 0 },
    { code: 'RM-00153', name: 'Monosodium glutamate (99%+ Purity)', unit: 'Kg', price: 0 },
    { code: 'RM-00154', name: 'Orange Flavour (Symrise)', unit: 'Kg', price: 0 },
    { code: 'RM-00155', name: 'Orange Flavour (BFF)', unit: 'Kg', price: 0 },
    { code: 'RM-00156', name: 'Clove', unit: 'Kg', price: 0 },
    { code: 'RM-00157', name: 'Coriander', unit: 'Kg', price: 0 },
    { code: 'RM-00158', name: 'Cumin Sweet (Fennel Seeds)', unit: 'Kg', price: 0 },
    { code: 'RM-00159', name: 'Ghee Flavour (Asia)', unit: 'Kg', price: 0 },
    { code: 'RM-00160', name: 'Mace', unit: 'Kg', price: 0 },
    { code: 'RM-00161', name: 'Nitric Acid', unit: 'Kg', price: 0 },
    { code: 'RM-00162', name: 'Potato', unit: 'Kg', price: 0 },
    { code: 'RM-00163', name: 'Sodium Lactate', unit: 'Kg', price: 0 },
    { code: 'RM-00164', name: 'Sucralose', unit: 'Kg', price: 0 },
    { code: 'RM-00165', name: 'Milk Flavour (Dohler)', unit: 'Kg', price: 0 }
  ]
}
export default db_materials
